services:
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=ports
    volumes:
      - influx-data:/var/lib/influxdb

  backend:
    build: ./backend
    container_name: monitor-backend
    ports:
      - "8000:8000"
    environment:
      - INFLUX_HOST=influxdb
    depends_on:
      - influxdb

  simulator:
    build: ./simulator
    container_name: monitor-simulator
    depends_on:
      - influxdb

  frontend:
    build: ./frontend
    container_name: monitor-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  influx-data:
